export const CLAVE_ID_EMPRESA = "IDEMPRESA";
export const CLAVE_CONJUNTO_OFERTAS_LABORALES = "CONJUNTOOFERTASLABORALES";
export const CLAVE_ULT_OFERTA_LABORAL = "ULTOFERTALABORAL";
export const CLAVE_SESION_USUARIO = "SESIONUSUARIO";
