export const CLAVE_ID_EMPRESA = "IDEMPRESA";
export const CLAVE_CONJUNTO_OFERTAS_LABORALES = "CONJUNTOOFERTASLABORALES";
export const CLAVE_ULT_OFERTA_LABORAL = "ULTOFERTALABORAL";
export const CLAVE_DATOS_BASICOS_EMPRESA = "DATOSBASICOSEMPRESA";
export const CLAVE_SESION_USUARIO = "SESIONUSUARIO";
export const CLAVE_TRABAJOS_EMPRESA = "TRABAJOSEMPRESA";

export const CLAVE_COOKIE = "NUESTRACOOKIE";
