name: Despliegue a GH Pages
on:
    workflow_run:
        workflows: ["Pruebas unitarias, integración y aceptación"]
        branches: [main]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Usa Node.js '12.x'
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Instalamos dependencias
              run: npm ci
            - name: Realizamos build
              run: npm run build
            - name: Duplicamos y renombramos index a 404
              run: cp dist/index.html dist/404.html
            - name: Commiteamos
              run: |
                  git config --local user.name "bot-actions"
                  git config --local user.email "migueldeolim1@gmail.com"
                  git add dist
                  git commit -m 'adding dist subtree' -a
            - name: Push cambios
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: dist
                  MESSAGE: "Despligue a GitHub Pages"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
